name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Поднимаем версию до 3.11, чтобы совпадала с target-версией

      - name: Настройкаа Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Установка системных зависимостей и Buildozer
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential ccache git libffi-dev libssl-dev python3-dev zip unzip zlib1g-dev \
            autoconf libtool pkg-config libltdl-dev
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install "cython<3.0.0" buildozer

      - name: Собрать APK
        run: |
          yes | buildozer -v android debug
